/**
 * Fallback, если /api/build/geo-presets недоступен (должен совпадать с сервером).
 */
export interface GeoPresetRowFallback {
  geoCode: string;
  geoLabel: string;
  recommendedPrimary: string;
  recommendedSecondary: string[];
  locales: string[];
  defaultLocale: string;
  defaultMultiLanguage: boolean;
  languageCount: number;
  templateCampaignId?: string | null;
}

export const FALLBACK_GEO_PRESETS: GeoPresetRowFallback[] = [
  {
    geoCode: "BD",
    geoLabel: "Bangladesh",
    recommendedPrimary: "English",
    recommendedSecondary: ["Bengali"],
    locales: ["en", "bn"],
    defaultLocale: "en",
    defaultMultiLanguage: true,
    languageCount: 2,
    templateCampaignId: null,
  },
  {
    geoCode: "UK",
    geoLabel: "United Kingdom",
    recommendedPrimary: "English",
    recommendedSecondary: [],
    locales: ["en"],
    defaultLocale: "en",
    defaultMultiLanguage: false,
    languageCount: 1,
    templateCampaignId: null,
  },
  {
    geoCode: "MULTI",
    geoLabel: "Multi-GEO",
    recommendedPrimary: "English",
    recommendedSecondary: [],
    locales: ["en"],
    defaultLocale: "en",
    defaultMultiLanguage: false,
    languageCount: 1,
    templateCampaignId: null,
  },
  {
    geoCode: "PK",
    geoLabel: "Pakistan",
    recommendedPrimary: "English",
    recommendedSecondary: [],
    locales: ["en"],
    defaultLocale: "en",
    defaultMultiLanguage: false,
    languageCount: 1,
    templateCampaignId: null,
  },
  {
    geoCode: "PH",
    geoLabel: "Philippines",
    recommendedPrimary: "English",
    recommendedSecondary: [],
    locales: ["en"],
    defaultLocale: "en",
    defaultMultiLanguage: false,
    languageCount: 1,
    templateCampaignId: null,
  },
  {
    geoCode: "BR",
    geoLabel: "Brazil",
    recommendedPrimary: "Portuguese (Brazil)",
    recommendedSecondary: [],
    locales: ["pt-br"],
    defaultLocale: "pt-br",
    defaultMultiLanguage: false,
    languageCount: 1,
    templateCampaignId: null,
  },
  {
    geoCode: "FR",
    geoLabel: "France",
    recommendedPrimary: "French",
    recommendedSecondary: [],
    locales: ["fr"],
    defaultLocale: "fr",
    defaultMultiLanguage: false,
    languageCount: 1,
    templateCampaignId: null,
  },
  {
    geoCode: "PT",
    geoLabel: "Portugal",
    recommendedPrimary: "Portuguese",
    recommendedSecondary: [],
    locales: ["pt"],
    defaultLocale: "pt",
    defaultMultiLanguage: false,
    languageCount: 1,
    templateCampaignId: null,
  },
  {
    geoCode: "ES",
    geoLabel: "Spain",
    recommendedPrimary: "Spanish",
    recommendedSecondary: [],
    locales: ["es"],
    defaultLocale: "es",
    defaultMultiLanguage: false,
    languageCount: 1,
    templateCampaignId: null,
  },
  {
    geoCode: "PRILKI",
    geoLabel: "Prilki Multi-GEO",
    recommendedPrimary: "English",
    recommendedSecondary: [],
    locales: ["en"],
    defaultLocale: "en",
    defaultMultiLanguage: false,
    languageCount: 1,
    templateCampaignId: null,
  },
  {
    geoCode: "VN",
    geoLabel: "Vietnam",
    recommendedPrimary: "Vietnamese",
    recommendedSecondary: [],
    locales: ["vi"],
    defaultLocale: "vi",
    defaultMultiLanguage: false,
    languageCount: 1,
    templateCampaignId: null,
  },
  {
    geoCode: "KEN",
    geoLabel: "Kenya",
    recommendedPrimary: "English",
    recommendedSecondary: [],
    locales: ["en"],
    defaultLocale: "en",
    defaultMultiLanguage: false,
    languageCount: 1,
    templateCampaignId: null,
  },
  {
    geoCode: "ARG",
    geoLabel: "Argentina",
    recommendedPrimary: "Spanish (Argentina)",
    recommendedSecondary: [],
    locales: ["es-ar"],
    defaultLocale: "es-ar",
    defaultMultiLanguage: false,
    languageCount: 1,
    templateCampaignId: null,
  },
  {
    geoCode: "NIG",
    geoLabel: "Nigeria",
    recommendedPrimary: "English",
    recommendedSecondary: [],
    locales: ["en"],
    defaultLocale: "en",
    defaultMultiLanguage: false,
    languageCount: 1,
    templateCampaignId: null,
  },
  {
    geoCode: "INDON",
    geoLabel: "Indonesia",
    recommendedPrimary: "Indonesian",
    recommendedSecondary: ["English"],
    locales: ["id", "en"],
    defaultLocale: "id",
    defaultMultiLanguage: true,
    languageCount: 2,
    templateCampaignId: null,
  },
  {
    geoCode: "MALA",
    geoLabel: "Malaysia",
    recommendedPrimary: "Malay",
    recommendedSecondary: ["English"],
    locales: ["ms", "en"],
    defaultLocale: "ms",
    defaultMultiLanguage: true,
    languageCount: 2,
    templateCampaignId: null,
  },
  {
    geoCode: "KAM",
    geoLabel: "Cambodia",
    recommendedPrimary: "Khmer",
    recommendedSecondary: ["English"],
    locales: ["km", "en"],
    defaultLocale: "km",
    defaultMultiLanguage: true,
    languageCount: 2,
    templateCampaignId: null,
  },
  {
    geoCode: "AUS",
    geoLabel: "Australia",
    recommendedPrimary: "English (Australia)",
    recommendedSecondary: [],
    locales: ["en-au"],
    defaultLocale: "en-au",
    defaultMultiLanguage: false,
    languageCount: 1,
    templateCampaignId: null,
  },
  {
    geoCode: "IN",
    geoLabel: "India",
    recommendedPrimary: "English",
    recommendedSecondary: [],
    locales: ["en"],
    defaultLocale: "en",
    defaultMultiLanguage: false,
    languageCount: 1,
    templateCampaignId: null,
  },
];

export const FALLBACK_LANG_OPTIONS: Array<{ label: string; locale: string }> = [
  { label: "English", locale: "en" },
  { label: "English (Australia)", locale: "en-au" },
  { label: "Bengali", locale: "bn" },
  { label: "Indonesian", locale: "id" },
  { label: "Malay", locale: "ms" },
  { label: "Khmer", locale: "km" },
  { label: "Vietnamese", locale: "vi" },
  { label: "French", locale: "fr" },
  { label: "Spanish", locale: "es" },
  { label: "Spanish (Argentina)", locale: "es-ar" },
  { label: "Portuguese", locale: "pt" },
  { label: "Portuguese (Brazil)", locale: "pt-br" },
  { label: "German", locale: "de" },
  { label: "Italian", locale: "it" },
  { label: "Hindi", locale: "hi" },
  { label: "Urdu", locale: "ur" },
  { label: "Filipino", locale: "fil" },
  { label: "Thai", locale: "th" },
  { label: "Russian", locale: "ru" },
  { label: "Ukrainian", locale: "uk" },
];
