import type { CSSProperties, ReactNode } from "react";
import { useLocation } from "react-router-dom";
import imagesData from "../pages/images.json";
import { useSeoHead } from "./SeoHead";

const SITE_NAME = (import.meta.env.VITE_SITE_NAME as string | undefined) || "Casino";
const AFFILIATE =
  (import.meta.env.VITE_AFFILIATE_URL as string | undefined) ||
  (import.meta.env.VITE_AFFILIATE_LINK as string | undefined) ||
  "#";

type ImagesIndex = Record<
  string,
  { src?: string; alt?: string; title?: string } | undefined
>;
const IMAGES = (imagesData as ImagesIndex) || {};

export type PageJson = {
  title?: string;
  description?: string;
  h1?: string;
  h1Description?: string;
  h1Image?: string;
  blocks?: Array<{
    blockType?: string;
    elements?: unknown[];
  }>;
};

/**
 * Resolves an image reference (e.g. "homepage1") to a real URL with sensible
 * fallbacks. Order of preference:
 *  1. images.json mapping (src + alt + title) — the file generated by the
 *     site-builder image pipeline.
 *  2. Already-absolute or root-relative URL.
 *  3. Bare key — assume it's the basename of a webp inside /images/.
 */
function resolveImage(ref: string): {
  src: string;
  alt: string;
  title: string;
} {
  if (!ref) return { src: "", alt: "", title: "" };

  const direct = ref.trim();

  if (direct.startsWith("http://") || direct.startsWith("https://")) {
    return { src: direct, alt: "", title: "" };
  }

  // Strip extension when looking up images.json — the manifest is keyed by
  // basename without ".webp".
  const lookupKey = direct.replace(/\.(webp|png|jpg|jpeg|gif|svg)$/i, "");
  const fromManifest = IMAGES[lookupKey] || IMAGES[direct];

  if (fromManifest && fromManifest.src) {
    const url = fromManifest.src.startsWith("/")
      ? fromManifest.src
      : `/${fromManifest.src}`;
    return {
      src: url,
      alt: fromManifest.alt || "",
      title: fromManifest.title || "",
    };
  }

  if (direct.startsWith("/")) {
    return { src: direct, alt: "", title: "" };
  }

  if (/\.(webp|png|jpg|jpeg|gif|svg)$/i.test(direct)) {
    return { src: `/images/${direct}`, alt: "", title: "" };
  }

  return { src: `/images/${direct}.webp`, alt: "", title: "" };
}

function renderElement(el: Record<string, unknown>, idx: number): ReactNode {
  const type = String(el.type || "").toLowerCase();
  const text =
    typeof el.text === "string"
      ? el.text
      : typeof el.content === "string"
        ? el.content
        : "";
  const titleField = typeof el.title === "string" ? el.title : "";

  switch (type) {
    case "h2":
    case "h3":
    case "heading": {
      const Tag = type === "h3" ? "h3" : "h2";
      const label = text || titleField;
      if (!label) return null;
      return (
        <Tag key={idx} className="sb-block-heading">
          {label}
        </Tag>
      );
    }
    case "paragraph":
    case "p": {
      if (!text) return null;
      return (
        <p key={idx} className="sb-block-p">
          {text}
        </p>
      );
    }
    case "list":
    case "list-large": {
      const raw = el.items;
      if (!Array.isArray(raw) || raw.length === 0) return null;
      return (
        <ul key={idx} className="sb-cards">
          {raw.map((item: unknown, j: number) => {
            const num = String(j + 1).padStart(2, "0");
            if (item && typeof item === "object" && "title" in item) {
              const it = item as { title?: string; description?: string };
              return (
                <li
                  key={j}
                  className="sb-card sb-reveal"
                  data-num={num}
                  style={{ "--sb-reveal-delay": `${j * 60}ms` } as CSSProperties}
                >
                  {it.title && (
                    <span className="sb-card-title">{it.title}</span>
                  )}
                  {it.description && (
                    <span className="sb-card-desc">{it.description}</span>
                  )}
                </li>
              );
            }
            if (typeof item === "string") {
              return (
                <li key={j} className="sb-card" data-num={num}>
                  <span className="sb-card-desc">{item}</span>
                </li>
              );
            }
            return null;
          })}
        </ul>
      );
    }
    case "glossarylist": {
      const raw = el.items;
      if (!Array.isArray(raw) || raw.length === 0) return null;
      return (
        <ul key={idx} className="sb-glossary">
          {raw.map((item: unknown, j: number) => {
            if (item && typeof item === "object" && "title" in item) {
              const it = item as { title?: string; description?: string };
              return (
                <li
                  key={j}
                  className="sb-glossary-item sb-reveal"
                  style={{ "--sb-reveal-delay": `${j * 50}ms` } as CSSProperties}
                >
                  {it.title && (
                    <span className="sb-glossary-title">{it.title}</span>
                  )}
                  {it.description && (
                    <span className="sb-glossary-desc">{it.description}</span>
                  )}
                </li>
              );
            }
            if (typeof item === "string") {
              return (
                <li key={j} className="sb-glossary-item">
                  <span className="sb-glossary-desc">{item}</span>
                </li>
              );
            }
            return null;
          })}
        </ul>
      );
    }
    case "image": {
      const ref = typeof el.src === "string" ? el.src : "";
      if (!ref) return null;
      const resolved = resolveImage(ref);
      const altOverride = typeof el.alt === "string" ? el.alt : "";
      return (
        <figure key={idx} className="sb-block-figure sb-reveal">
          <img
            src={resolved.src}
            alt={altOverride || resolved.alt || ""}
            title={resolved.title || undefined}
            loading="lazy"
            decoding="async"
            className="sb-block-img"
          />
        </figure>
      );
    }
    case "button": {
      const label = text || titleField || String(el.label || "Play Now");
      const href =
        typeof el.href === "string" && el.href.startsWith("http")
          ? el.href
          : AFFILIATE;
      return (
        <p key={idx} className="sb-block-btn-wrap">
          <a className="sb-block-btn" href={href} rel="noopener noreferrer">
            {label}
          </a>
        </p>
      );
    }
    default:
      return null;
  }
}

function HeroBanner({ data }: { data: PageJson }) {
  const heroRef = data.h1Image ? resolveImage(data.h1Image) : null;
  const heroStyle: CSSProperties | undefined = heroRef?.src
    ? { backgroundImage: `url(${heroRef.src})` }
    : undefined;
  return (
    <section className="sb-hero">
      {heroStyle ? (
        <div className="sb-hero-bg" style={heroStyle} role="img" aria-label={heroRef?.alt || ""} />
      ) : (
        <div className="sb-hero-bg sb-hero-fallback" aria-hidden="true" />
      )}
      <div className="sb-hero-inner">
        <span className="sb-hero-eyebrow">Premium online casino</span>
        {data.h1 && <h1 className="sb-h1">{data.h1}</h1>}
        {data.h1Description && (
          <p className="sb-h1-desc">{data.h1Description}</p>
        )}
        <div className="sb-hero-actions">
          <a className="sb-btn sb-btn-primary" href={AFFILIATE} rel="noopener noreferrer">
            Play {SITE_NAME}
          </a>
          <a className="sb-btn sb-btn-ghost" href="#sb-content">
            Explore games
          </a>
        </div>
        <div className="sb-hero-stats">
          <div className="sb-hero-stat">
            <strong>1000+</strong>
            <span>Games</span>
          </div>
          <div className="sb-hero-stat">
            <strong>24/7</strong>
            <span>Live Support</span>
          </div>
          <div className="sb-hero-stat">
            <strong>2 min</strong>
            <span>Fast Payouts</span>
          </div>
        </div>
      </div>
    </section>
  );
}

export function PageView({ data }: { data: PageJson | null | undefined }) {
  const location = useLocation();

  // Per-route SEO sync: title/description/canonical/OG/Twitter. Called
  // unconditionally (rules of hooks) — when there is no page data we
  // still set a generic title so route changes never leave a stale tab
  // label from a prior page.
  useSeoHead({
    title:
      (data && typeof data === "object" && (data.title || data.h1)) ||
      undefined,
    description:
      (data && typeof data === "object" &&
        (data.description || data.h1Description)) ||
      undefined,
    pathname: location.pathname,
  });

  if (!data || typeof data !== "object") {
    return (
      <div className="sb-placeholder">
        <p>Нет данных страницы. Сгенерируйте и сохраните страницы в Site Builder.</p>
      </div>
    );
  }

  const blocks = Array.isArray(data.blocks) ? data.blocks : [];

  return (
    <article className="sb-page">
      <HeroBanner data={data} />

      <div id="sb-content" className="sb-content">
        {blocks.map((block, bi) => (
          <section
            key={bi}
            className="sb-section sb-reveal"
            style={{ "--sb-reveal-delay": `${bi * 80}ms` } as CSSProperties}
            {...(block.blockType ? { "data-block": block.blockType } : {})}
          >
            {Array.isArray(block.elements) &&
              block.elements.map((raw, ei) =>
                raw && typeof raw === "object"
                  ? renderElement(raw as Record<string, unknown>, ei)
                  : null
              )}
          </section>
        ))}
      </div>
    </article>
  );
}
