import {
  getStructureTemplateForPage,
  getStructureForBlock,
} from "./templates.js";

export const getStructureTemplate = (pageType: string, blocks?: string[]) => {
  return getStructureTemplateForPage(pageType, blocks);
};

/**
 * Per-page-type "search intent" hint: nudges the model to focus title +
 * description on what users actually search for that page so meta is
 * SEO-relevant rather than generic brand puffery.
 */
function pageSeoBrief(pageType: string, brand: string): string {
  const map: Record<string, string> = {
    homepage: `the official ${brand} brand and its main offer (welcome bonus, top games, instant payouts)`,
    casino: `${brand} casino games, table games, jackpots and live dealers`,
    slots: `${brand} slot games, megaways, RTP, bonus rounds and free spins`,
    games: `${brand} game library — slots, table games, live casino, instant wins`,
    betting: `${brand} sports betting, odds, in-play and major events`,
    app: `${brand} mobile app for iOS and Android: install, sign up and play on the go`,
    login: `${brand} login and account access — secure sign-in, password recovery`,
  };
  return map[pageType] || `the ${brand} ${pageType} page`;
}

export const generateSingleBlockSystemPrompt = (
  language: string,
  brand: string,
  country: string,
  domain: string,
  affiliateLink: string,
  pageLabel: string,
  /** Один объект блока из getStructureForBlock (blockType + elements) */
  blockSkeleton: Record<string, unknown>
): string => {
  const geoLine =
    country === "NO COUNTRY"
      ? "(do NOT mention any country/region in this block)"
      : `(you may mention "${country}" once if natural)`;

  const skeletonJson = JSON.stringify({ blocks: [blockSkeleton] }, null, 2);

  return `You are a casino content generator that outputs JSON only.

Task: generate text content for ONE section block on page "${pageLabel}" for brand "${brand}" (${domain}).

CRITICAL output shape:
- Return a single JSON object with exactly ONE top-level key: "blocks".
- "blocks" MUST be an array with exactly ONE object.
- That object MUST match the structure below (same keys: blockType, elements). Fill every "text", list item "title" and "description", etc. in ${language}.
- Do NOT output page-level fields (no "title", "description", "h1", "h1Description" at the root). ONLY "blocks".

Structure to fill (placeholder layout — replace empties with real content):
${skeletonJson}

Rules:
- Output valid JSON only (no markdown fences).
- Brand "${brand}" must appear naturally in the block copy (not every sentence).
- Each paragraph element: 2–4 sentences of flowing prose — never bullet points, dashes or line-by-line enumerations inside a paragraph (weave multiple items into a natural sentence instead).
- Each list / list-large / glossaryList: 3–10 items.
- Any "faq" element MUST contain AT LEAST 5 items; each item "title" is a question ending with "?" and "description" is a concise 1–3 sentence answer mentioning "${brand}" where natural. Do NOT duplicate questions.
- Affiliate context only if relevant; primary url hint: ${affiliateLink}
${geoLine}

JSON must start with '{' and end with '}'.`;
};

export const generateSystemPrompt = (
  language: string,
  brand: string,
  country: string,
  domain: string,
  affiliateLink: string,
  pageType: string,
  structureTemplate: any
): string => {
  const seoBrief = pageSeoBrief(pageType, brand);
  const geoLine =
    country === "NO COUNTRY"
      ? "(do NOT include any country/region in title or description)"
      : `(safe to include "${country}" once when natural, never twice)`;

  return `You are a casino content generator that outputs JSON only.

Your task: create ${pageType} page content for an online casino brand.

Rules:

- Output must be valid JSON (no markdown, no explanations).
- Use the exact JSON structure as in the template below.
- Do not remove or rename fields.
- You may only fill "text", "title", and "description" fields with your generated content in ${language}.
- Each "h2" is a heading generated by you.
- Each "paragraph" contains 2–4 sentences of flowing prose. NEVER format a paragraph as a bullet/numbered list and NEVER use dashes, hyphens or "•" to enumerate items inside a paragraph. If you need to mention several things in a paragraph, weave them into a natural sentence (e.g. "popular titles such as Chicken Road, Lucky Spin and Sweet Bonanza"), do NOT list them line by line.
- Only "list", "list-large" and "glossaryList" elements may contain enumerations; everything else must be normal sentences.
- Each "list", "list-large" or "glossaryList" must contain 3–10 logically fitting items.
- Any element of type "faq" (FAQ block) MUST contain AT LEAST 5 items. Each FAQ item: "title" is a real user question that ends with "?", "description" is a clear, helpful 1–3 sentence answer. Questions must be specific to this ${pageType} page (e.g. account, bonuses, payments, games, app, login) and mention "${brand}" naturally where it fits. Do NOT duplicate questions.
- Replace BRAND with "${brand}" naturally in text.
- h1 and h1Description must follow the same tone, structure, and style. Use energetic, natural phrasing and emotional balance.
- h1 starts with the brand name and has an energetic, natural tagline.

SEO requirements for the top-level "title" and "description":
- Topic/intent for THIS page = ${seoBrief}.
- "title": 50–60 characters TOTAL (including the brand). ALWAYS start with the brand "${brand}", then an em dash or hyphen, then the unique page-specific phrase (keywords, intent). Example pattern: "${brand} — <unique page headline>" or "${brand} - Slots & Jackpots".
- Never put the brand only at the end; brand must be the first visible token(s).
- "description": 140–160 characters TOTAL. One sentence. Must contain the page's primary keyword AND a benefit/CTA (play, claim, sign up, deposit, win, explore). End with a clean period.
- Both fields MUST be UNIQUE for this page — never copy phrasing from other pages of the site.
- Do NOT pad with filler like "Welcome to" or "We are…". Lead with action/value.
- Do NOT keyword-stuff. Each keyword appears at most twice across title+description combined.
- Avoid clickbait/superlatives banned by Google: "best ever", "#1", "guaranteed". Prefer factual benefits.
- Do NOT wrap title/description in quotes; they are plain strings.
- Geo handling for title/description ${geoLine}.

IF the value of COUNTRY is "NO COUNTRY":
    - Do NOT mention or imply any country, location, region, or nationality.
ELSE:
    - Mention the country naturally in text (e.g., "in ${country}"), only when appropriate.

- Do not include comments, markdown, or explanations.
Required top-level keys:
"title", "description", "h1", "h1Description","blocks"
Block structure reference (blocks must be an array):
{
  "blocks": ${JSON.stringify(structureTemplate, null, 2)}
}
JSON Output Enforcement:
- Output must start with '{' and end with '}'.
- Never include line breaks, explanations, or non-JSON text outside the object.
- If you are unsure, output nothing except the JSON object.`;
};

/**
 * Builds the "Block keyword guidance" section appended to the user
 * prompt. Each entry maps a block name to a free-form comma-separated
 * list of keywords/topics the user wants this block to cover. The
 * model is instructed to weave those keywords into the block content
 * naturally — they drive what the block is actually about, not just
 * its title.
 */
export const buildBlockKeywordsGuidance = (
  blockKeywords?: Record<string, string>
): string => {
  if (!blockKeywords) return "";
  const entries = Object.entries(blockKeywords)
    .map(([block, raw]) => {
      const cleaned = typeof raw === "string" ? raw.trim() : "";
      if (!cleaned) return null;
      const list = cleaned
        .split(",")
        .map((k) => k.trim())
        .filter(Boolean);
      if (list.length === 0) return null;
      return `- Block "${block}": ${list.join(", ")}`;
    })
    .filter((line): line is string => Boolean(line));
  if (entries.length === 0) return "";
  return `\nBlock keyword guidance (each block MUST be written around the listed keywords/topics — cover every keyword at least once, naturally, in the block's text/h2/list items as appropriate; do NOT just paste them in, weave them into the narrative):\n${entries.join(
    "\n"
  )}`;
};

export const generateUserPrompt = (
  brand: string,
  language: string,
  country: string,
  blocks: string[],
  pageType: string,
  uniquenessHint?: string,
  blockKeywords?: Record<string, string>,
  referenceGuidance?: string
): string => {
  // The uniqueness hint is appended verbatim to the user prompt so the
  // model can use it as a signal NOT to repeat phrasing. Caller should
  // pass a short snippet such as "session id 1778264597-3" or a short
  // list of titles/descriptions already used by sibling pages.
  const uniquenessBlock = uniquenessHint
    ? `\nUniqueness signal (do NOT echo back, only use to vary phrasing):\n${uniquenessHint}\nDO NOT reuse any of the exact title or description strings above. Pick fresh wording, synonyms and angle.`
    : "";

  const keywordsBlock = buildBlockKeywordsGuidance(blockKeywords);
  const referenceBlock = referenceGuidance ? `\n${referenceGuidance}` : "";

  return `Generate ${pageType} page JSON for brand ${brand} in ${language} for ${country}.
Include blocks: ${blocks.join(", ")}.
The brand name "${brand}" MUST be used naturally throughout the text and is a required keyword.
Do NOT start sentences with the construction "At ${brand}".  
Instead, use alternative sentence openings such as:
- "${brand} offers..."
- "With ${brand}, users can..."
- "${brand} provides..."
- "Players can..."
- "Users enjoy..."

Never remove or avoid the brand name entirely.
Follow the structure above exactly.${keywordsBlock}${uniquenessBlock}${referenceBlock}`;
};
