import {
  getStructureTemplateForPage,
  getStructureForBlock,
} from "./templates.js";

export const getStructureTemplate = (pageType: string, blocks?: string[]) => {
  return getStructureTemplateForPage(pageType, blocks);
};

/**
 * Per-page-type "search intent" hint: nudges the model to focus title +
 * description on what users actually search for that page so meta is
 * SEO-relevant rather than generic brand puffery.
 */
function pageSeoBrief(pageType: string, brand: string): string {
  const map: Record<string, string> = {
    homepage: `the official ${brand} brand and its main offer (welcome bonus, top games, instant payouts)`,
    casino: `${brand} casino games, table games, jackpots and live dealers`,
    slots: `${brand} slot games, megaways, RTP, bonus rounds and free spins`,
    games: `${brand} game library — slots, table games, live casino, instant wins`,
    betting: `${brand} sports betting, odds, in-play and major events`,
    app: `${brand} mobile app for iOS and Android: install, sign up and play on the go`,
    login: `${brand} login and account access — secure sign-in, password recovery`,
  };
  return map[pageType] || `the ${brand} ${pageType} page`;
}

export const generateSystemPrompt = (
  language: string,
  brand: string,
  country: string,
  domain: string,
  affiliateLink: string,
  pageType: string,
  structureTemplate: any
): string => {
  const seoBrief = pageSeoBrief(pageType, brand);
  const geoLine =
    country === "NO COUNTRY"
      ? "(do NOT include any country/region in title or description)"
      : `(safe to include "${country}" once when natural, never twice)`;

  return `You are a casino content generator that outputs JSON only.

Your task: create ${pageType} page content for an online casino brand.

Rules:

- Output must be valid JSON (no markdown, no explanations).
- Use the exact JSON structure as in the template below.
- Do not remove or rename fields.
- You may only fill "text", "title", and "description" fields with your generated content in ${language}.
- Each "h2" is a heading generated by you.
- Each "paragraph" contains 2–4 sentences.
- Each "list", "list-large" or "glossaryList" must contain 3–10 logically fitting items.
- Replace BRAND with "${brand}" naturally in text.
- h1 and h1Description must follow the same tone, structure, and style. Use energetic, natural phrasing and emotional balance.
- h1 starts with the brand name and has an energetic, natural tagline.

SEO requirements for the top-level "title" and "description":
- Topic/intent for THIS page = ${seoBrief}.
- "title": 50–60 characters TOTAL (including the brand). Put the strongest keyword FIRST, then a colon or pipe, then the brand. Example pattern: "<Primary keyword>: <unique value> | ${brand}".
- "description": 140–160 characters TOTAL. One sentence. Must contain the page's primary keyword AND a benefit/CTA (play, claim, sign up, deposit, win, explore). End with a clean period.
- Both fields MUST be UNIQUE for this page — never copy phrasing from other pages of the site.
- Do NOT pad with filler like "Welcome to" or "We are…". Lead with action/value.
- Do NOT keyword-stuff. Each keyword appears at most twice across title+description combined.
- Avoid clickbait/superlatives banned by Google: "best ever", "#1", "guaranteed". Prefer factual benefits.
- Do NOT wrap title/description in quotes; they are plain strings.
- Geo handling for title/description ${geoLine}.

IF the value of COUNTRY is "NO COUNTRY":
    - Do NOT mention or imply any country, location, region, or nationality.
ELSE:
    - Mention the country naturally in text (e.g., "in ${country}"), only when appropriate.

- Do not include comments, markdown, or explanations.
Required top-level keys:
"title", "description", "h1", "h1Description","blocks"
Block structure reference (blocks must be an array):
{
  "blocks": ${JSON.stringify(structureTemplate, null, 2)}
}
JSON Output Enforcement:
- Output must start with '{' and end with '}'.
- Never include line breaks, explanations, or non-JSON text outside the object.
- If you are unsure, output nothing except the JSON object.`;
};

/**
 * Builds the "Block keyword guidance" section appended to the user
 * prompt. Each entry maps a block name to a free-form comma-separated
 * list of keywords/topics the user wants this block to cover. The
 * model is instructed to weave those keywords into the block content
 * naturally — they drive what the block is actually about, not just
 * its title.
 */
export const buildBlockKeywordsGuidance = (
  blockKeywords?: Record<string, string>
): string => {
  if (!blockKeywords) return "";
  const entries = Object.entries(blockKeywords)
    .map(([block, raw]) => {
      const cleaned = typeof raw === "string" ? raw.trim() : "";
      if (!cleaned) return null;
      const list = cleaned
        .split(",")
        .map((k) => k.trim())
        .filter(Boolean);
      if (list.length === 0) return null;
      return `- Block "${block}": ${list.join(", ")}`;
    })
    .filter((line): line is string => Boolean(line));
  if (entries.length === 0) return "";
  return `\nBlock keyword guidance (each block MUST be written around the listed keywords/topics — cover every keyword at least once, naturally, in the block's text/h2/list items as appropriate; do NOT just paste them in, weave them into the narrative):\n${entries.join(
    "\n"
  )}`;
};

export const generateUserPrompt = (
  brand: string,
  language: string,
  country: string,
  blocks: string[],
  pageType: string,
  uniquenessHint?: string,
  blockKeywords?: Record<string, string>
): string => {
  // The uniqueness hint is appended verbatim to the user prompt so the
  // model can use it as a signal NOT to repeat phrasing. Caller should
  // pass a short snippet such as "session id 1778264597-3" or a short
  // list of titles/descriptions already used by sibling pages.
  const uniquenessBlock = uniquenessHint
    ? `\nUniqueness signal (do NOT echo back, only use to vary phrasing):\n${uniquenessHint}\nDO NOT reuse any of the exact title or description strings above. Pick fresh wording, synonyms and angle.`
    : "";

  const keywordsBlock = buildBlockKeywordsGuidance(blockKeywords);

  return `Generate ${pageType} page JSON for brand ${brand} in ${language} for ${country}.
Include blocks: ${blocks.join(", ")}.
The brand name "${brand}" MUST be used naturally throughout the text and is a required keyword.
Do NOT start sentences with the construction "At ${brand}".  
Instead, use alternative sentence openings such as:
- "${brand} offers..."
- "With ${brand}, users can..."
- "${brand} provides..."
- "Players can..."
- "Users enjoy..."

Never remove or avoid the brand name entirely.
Follow the structure above exactly.${keywordsBlock}${uniquenessBlock}`;
};
